# Generated by Django 2.2.1 on 2020-01-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=120)),
                ('data', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
