# Generated by Django 2.2.1 on 2020-01-29 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='signup',
            name='confirm',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
